services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: code-leveling-app:latest
    container_name: code-leveling-app
    restart: unless-stopped
    pull_policy: build
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
